In [12]:
import psycopg2 as pg
import pandas.io.sql as psql
import pandas as pd

In [13]:
query_simtest = """
SELECT
  trim('"' FROM block::text )::int as block,
  trim('"' FROM min::text )::int as min,
  s.holding,
  s.acks,
  s.msgqueue,
  s.inmsgqueue,
  s.apiqueue,
  s.ackqueue,
  s.timermsg,
  ts::text::time
FROM (SELECT
  --mt     | "LIST_SIZES Holding: %v, Acks: %v, MsgQueue: %v, InMsgQueue: %v, APIQueue: %v, AckQueue: %v, TimerMsg: %v "
  run,
  e->'log'->'height' as block,
  e->'log'->'min' as min,
  e->'log'->'event'->0 as holding,
  e->'log'->'event'->1 as acks,
  e->'log'->'event'->2 as msgqueue,
  e->'log'->'event'->3 as inmsgqueue,
  e->'log'->'event'->4 as apiqueue,
  e->'log'->'event'->5 as ackqueue,
  e->'log'->'event'->6 as timermsg,
  e->'log'->'event'->7 as fmt,
  e->'ts' as ts
  --e as l
FROM
  logs
) as s

WHERE
  s.fmt::varchar like '%LIST_SIZES%'
ORDER BY ts;

"""

connection = pg.connect("host='localdb' dbname=load user=load password='load'")

In [14]:
df = pd.read_sql_query(query_simtest,con=connection)
print(df)

      block  min  holding  acks  msgqueue  inmsgqueue  apiqueue  ackqueue  \
0         5    1      185     0        14           0        32         0
1         5    1        0     0         0           0         0         0
2         5    1        0     0         0           0         0         0
3         5    1      377     0         0          21         0         0
4         5    1       28     0         0           0         0         0
5         5    1       71     0         0          19         0         4
6         5    1      327     0         0          51         0         0
7         5    1       50     0         0          17         0         0
8         5    1       50     0         0           0         0         0
9         5    2      246     0         9           0         0         1
10        5    2      425     0         0           0         0         0
11        5    2      214     1         0           0         0         0
12        5    2      267     0         0           0         0         0
13        5    2      181     3         0          24         0        32
14        5    2      145    30         0          52         0         0
15        5    2      116     0         0           3         0         0
16        5    2        5     0         0          32         0         0
17        5    2       20    33         0          39         0         9
18        5    2        0    52         0           0         0         0
19        5    3      119     0        27           0         0         0
20        5    2        2   129        44           0         0         0
21        5    3      249     1         0           7         0        13
22        5    3       35     1         8          14         0        23
23        5    3       56     0         0           1         0         0
24        5    3      200     1         0          19         0        10
25        5    3        7    20         0          11         0        27
26        5    3       15     0        33           0         0         1
27        5    4      108    13         0          39         0         0
28        5    4      191     0         0           0         0         0
29        5    4      159     1         0          38         0         0
...     ...  ...      ...   ...       ...         ...       ...       ...
3426     18    0        1     0         0           0         0         0
3427     18    0        0     0         0           0         0         0
3428     18    0        0     0         0           0         0         0
3429     18    0        0     0         0           0         0         0
3430     18    0        1     0         0           0         0         0
3431     18    0        0     0         0           0         0         0
3432     18    0        0     0         0           0         0         0
3433     18    0        1     0         0           0         0         0
3434     18    0        0     0         0           0         0         0
3435     18    0        0     0         0           0         0         0
3436     18    0        0     0         0           0         0         0
3437     18    0        1     0         0           0         0         0
3438     18    0        0     0         0           0         0         0
3439     18    0        0     0         0           0         0         0
3440     18    0        1     0         0           0         0         0
3441     18    0        0     0         0           0         0         0
3442     18    0        0     0         0           0         0         0
3443     18    0        1     0         0           0         0         0
3444     18    0        0     0         0           0         0         0
3445     18    0        1     0         0           0         0         0
3446     18    0        0     0         0           0         0         0
3447     18    0        0     0         0           0         0         0
3448     18    0        0     0         0           0         0         0
3449     18    0        1     0         0           0         0         0
3450     18    0        0     0         0           0         0         0
3451     18    0        0     0         0           0         0         0
3452     18    0        1     0         0           0         0         0
3453     18    0        1     0         0           0         0         0
3454     18    0        0     0         0           0         0         0
3455     18    0        0     0         0           0         0         0

      timermsg               ts
0            0  00:20:55.494000
1            0  00:20:55.497000
2            0  00:20:55.497000
3            0  00:20:56.494000
4            0  00:20:56.494000
5            0  00:20:56.494000
6            0  00:20:57.493000
7            0  00:20:57.495000
8            0  00:20:57.495000
9            0  00:20:58.495000
10           0  00:20:58.495000
11           0  00:20:58.495000
12           0  00:20:59.495000
13           0  00:20:59.496000
14           0  00:20:59.497000
15           0  00:21:00.495000
16           0  00:21:00.496000
17           0  00:21:00.497000
18           0  00:21:01.494000
19           0  00:21:01.494000
20           0  00:21:01.494000
21           0  00:21:02.493000
22           0  00:21:02.494000
23           0  00:21:02.494000
24           0  00:21:03.495000
25           0  00:21:03.498000
26           0  00:21:03.498000
27           0  00:21:04.493000
28           0  00:21:04.493000
29           0  00:21:04.493000
...        ...              ...
3426         0  01:06:48.532000
3427         0  01:06:48.532000
3428         0  01:06:48.532000
3429         0  01:06:49.532000
3430         0  01:06:49.532000
3431         0  01:06:49.532000
3432         0  01:06:50.532000
3433         0  01:06:50.532000
3434         0  01:06:50.532000
3435         0  01:06:51.532000
3436         0  01:06:51.532000
3437         0  01:06:51.532000
3438         0  01:06:52.532000
3439         0  01:06:52.532000
3440         0  01:06:52.532000
3441         0  01:06:53.532000
3442         0  01:06:53.532000
3443         0  01:06:53.532000
3444         0  01:06:54.532000
3445         0  01:06:54.532000
3446         0  01:06:54.532000
3447         0  01:06:55.532000
3448         0  01:06:55.532000
3449         0  01:06:55.532000
3450         0  01:06:56.532000
3451         0  01:06:56.532000
3452         0  01:06:56.532000
3453         0  01:06:57.532000
3454         0  01:06:57.532000
3455         0  01:06:57.532000

[3456 rows x 10 columns]

In [16]:
import plotly.plotly as py
import plotly.graph_objs as go

import pandas as pd
from datetime import datetime

data = [
    go.Scatter(x=df['ts'], y=df['holding'], name='holding'),
    go.Scatter(x=df['ts'], y=df['acks'], name='acks'),
    go.Scatter(x=df['ts'], y=df['msgqueue'], name='msgqueue'),
    go.Scatter(x=df['ts'], y=df['inmsgqueue'], name='inmsgqueue'),
]

py.iplot(data, filename = 'holding_msg_queues_comp_with_delay')