In [2]:
import psycopg2 as pg
import pandas.io.sql as psql
import pandas as pd

In [3]:
query_simtest = """
SELECT
  trim('"' FROM block::text )::int as block,
  trim('"' FROM min::text )::int as min,
  s.holding,
  s.acks,
  s.msgqueue,
  s.inmsgqueue,
  s.apiqueue,
  s.ackqueue,
  s.timermsg,
  ts::text::time
FROM (SELECT
  --mt     | "LIST_SIZES Holding: %v, Acks: %v, MsgQueue: %v, InMsgQueue: %v, APIQueue: %v, AckQueue: %v, TimerMsg: %v "
  run,
  e->'log'->'height' as block,
  e->'log'->'min' as min,
  e->'log'->'event'->0 as holding,
  e->'log'->'event'->1 as acks,
  e->'log'->'event'->2 as msgqueue,
  e->'log'->'event'->3 as inmsgqueue,
  e->'log'->'event'->4 as apiqueue,
  e->'log'->'event'->5 as ackqueue,
  e->'log'->'event'->6 as timermsg,
  e->'log'->'event'->7 as fmt,
  e->'ts' as ts
  --e as l
FROM
  logs
) as s

WHERE
  s.fmt::varchar like '%LIST_SIZES%'
ORDER BY ts;

"""

connection = pg.connect("host='localdb' dbname=load user=load password='load'")

In [4]:
df = pd.read_sql_query(query_simtest,con=connection)
print(df)

      block  min  holding  acks  msgqueue  inmsgqueue  apiqueue  ackqueue  \
0         5    1      185     0        14           0        32         0
1         5    1        0     0         0           0         0         0
2         5    1        0     0         0           0         0         0
3         5    1       71     0         0          19         0         4
4         5    1      377     0         0          21         0         0
5         5    1       28     0         0           0         0         0
6         5    1      327     0         0          51         0         0
7         5    1       50     0         0          17         0         0
8         5    1       50     0         0           0         0         0
9         5    2      214     1         0           0         0         0
10        5    2      425     0         0           0         0         0
11        5    2      246     0         9           0         0         1
12        5    2      267     0         0           0         0         0
13        5    2      181     3         0          24         0        32
14        5    2      145    30         0          52         0         0
15        5    2      116     0         0           3         0         0
16        5    2        5     0         0          32         0         0
17        5    2       20    33         0          39         0         9
18        5    2        2   129        44           0         0         0
19        5    2        0    52         0           0         0         0
20        5    3      119     0        27           0         0         0
21        5    3      249     1         0           7         0        13
22        5    3       35     1         8          14         0        23
23        5    3       56     0         0           1         0         0
24        5    3      200     1         0          19         0        10
25        5    3        7    20         0          11         0        27
26        5    3       15     0        33           0         0         1
27        5    4      108    13         0          39         0         0
28        5    4      159     1         0          38         0         0
29        5    4      191     0         0           0         0         0
...     ...  ...      ...   ...       ...         ...       ...       ...
1500     17    0        1     0         0           0         0         0
1501     17    0        0     0         0           0         0         0
1502     17    0        0     0         0           0         0         0
1503     17    0        0     0         0           0         0         0
1504     17    0        0     0         0           0         0         0
1505     17    0        1     0         0           0         0         0
1506     17    0        1     0         0           0         0         0
1507     17    0        0     0         0           0         0         0
1508     17    0        0     0         0           0         0         0
1509     17    0        0     0         0           0         0         0
1510     17    0        0     0         0           0         0         0
1511     17    0        1     0         0           0         0         0
1512     17    0        1     0         0           0         0         0
1513     17    0        0     0         0           0         0         0
1514     17    0        0     0         0           0         0         0
1515     17    0        0     0         0           0         0         0
1516     17    0        0     0         0           0         0         0
1517     17    0        1     0         0           0         0         0
1518     17    0        0     0         0           0         0         0
1519     17    0        0     0         0           0         0         0
1520     17    0        1     0         0           0         0         0
1521     17    0        0     0         0           0         0         0
1522     17    0        1     0         0           0         0         0
1523     17    0        0     0         0           0         0         0
1524     17    0        1     0         0           0         0         0
1525     17    0        0     0         0           0         0         0
1526     17    0        0     0         0           0         0         0
1527     17    0        0     0         0           0         0         0
1528     17    0        0     0         0           0         0         0
1529     17    0        1     0         0           0         0         0

      timermsg               ts
0            0  00:20:55.494000
1            0  00:20:55.497000
2            0  00:20:55.497000
3            0  00:20:56.494000
4            0  00:20:56.494000
5            0  00:20:56.494000
6            0  00:20:57.493000
7            0  00:20:57.495000
8            0  00:20:57.495000
9            0  00:20:58.495000
10           0  00:20:58.495000
11           0  00:20:58.495000
12           0  00:20:59.495000
13           0  00:20:59.496000
14           0  00:20:59.497000
15           0  00:21:00.495000
16           0  00:21:00.496000
17           0  00:21:00.497000
18           0  00:21:01.494000
19           0  00:21:01.494000
20           0  00:21:01.494000
21           0  00:21:02.493000
22           0  00:21:02.494000
23           0  00:21:02.494000
24           0  00:21:03.495000
25           0  00:21:03.498000
26           0  00:21:03.498000
27           0  00:21:04.493000
28           0  00:21:04.493000
29           0  00:21:04.493000
...        ...              ...
1500         0  00:29:15.494000
1501         0  00:29:15.494000
1502         0  00:29:15.494000
1503         0  00:29:16.494000
1504         0  00:29:16.494000
1505         0  00:29:16.494000
1506         0  00:29:17.494000
1507         0  00:29:17.494000
1508         0  00:29:17.494000
1509         0  00:29:18.494000
1510         0  00:29:18.494000
1511         0  00:29:18.494000
1512         0  00:29:19.494000
1513         0  00:29:19.494000
1514         0  00:29:19.494000
1515         0  00:29:20.494000
1516         0  00:29:20.494000
1517         0  00:29:20.494000
1518         0  00:29:21.493000
1519         0  00:29:21.494000
1520         0  00:29:21.494000
1521         0  00:29:22.494000
1522         0  00:29:22.494000
1523         0  00:29:22.494000
1524         0  00:29:23.494000
1525         0  00:29:23.494000
1526         0  00:29:23.494000
1527         0  00:29:24.493000
1528         0  00:29:24.494000
1529         0  00:29:24.494000

[1530 rows x 10 columns]

In [9]:
import plotly.plotly as py
import plotly.graph_objs as go

import pandas as pd
from datetime import datetime

data = [
    go.Scatter(x=df['ts'], y=df['holding'], name='holding'),
    go.Scatter(x=df['ts'], y=df['acks'], name='acks'),
    go.Scatter(x=df['ts'], y=df['msgqueue'], name='msgqueue'),
    go.Scatter(x=df['ts'], y=df['inmsgqueue'], name='inmsgqueue'),
]

py.iplot(data, filename = 'holding_msg_queues')